"""Mechanism certificate for Evidence Commons v0.

Enumerates every profile of the scripted strategy set {contributor, freerider}
for all 3 agents under all four 2x2 institutions (32 deterministic episodes)
and checks, by exact computation on the sealed summaries:

  C1. Free-riding temptation: does switching contributor -> freerider, holding
      the others fixed, ever raise the switcher's utility? (per institution)
  C2. Collective stakes: does all-contribute beat all-freeride in total
      utility? (per institution)
  C3. Intervention invariance: for IDENTICAL behaviour profiles, aggregate vs
      attributable accountability changes only the DISTRIBUTION of credit,
      never the briefing, collective quality, or total utility — i.e. the
      intervention changes attribution, not the task.

Scope honesty: these are theorems only over the enumerated scripted strategy
set. Any claim about the full strategy space (or LLM behaviour) is a
SIMULATION HYPOTHESIS and is labelled as such in the generated certificate.

Writes MECHANISM_CERTIFICATE.md next to this script.
"""

import itertools
import shutil
import sys
import tempfile
from fractions import Fraction
from pathlib import Path

STUDY_DIR = Path(__file__).parent
REPO = STUDY_DIR.parent.parent
sys.path.insert(0, str(REPO / "src"))

from collaborative_hill.engine.runner import RunConfig, run_episode  # noqa: E402
from collaborative_hill.engine.store import RunPaths  # noqa: E402
from collaborative_hill.experiments.scenario import (  # noqa: E402
    NarrativeSkin,
    ScenarioSpec,
    compile_scenario,
)
from collaborative_hill.experiments.study import build_policies  # noqa: E402
from generate_study import CONDITIONS, build_scenario  # noqa: E402

AGENTS = ("a1", "a2", "a3")
STRATS = ("contributor", "freerider")
POLICY = {"contributor": {"name": "ec_contributor"}, "freerider": {"name": "ec_freerider"}}
INSTITUTIONS = [(acc, topo) for acc in ("aggregate", "attributable")
                for topo in ("private", "shared_ledger")]


def run_profile(accountability: str, topology: str, profile: tuple[str, ...],
                workdir: Path) -> dict:
    spec = build_scenario(
        f"cert-{accountability[:3]}-{topology[:4]}-" + "".join(s[0] for s in profile),
        accountability, topology, [POLICY[s] for s in profile],
    )
    skin = NarrativeSkin(skin_id="certificate-plain", title="certificate")
    resolved = compile_scenario(spec, skin)
    paths = RunPaths(workdir / spec.scenario_id).create()
    config = RunConfig(study_id="001-certificate", run_id=spec.scenario_id,
                       seed_root=(0, spec.scenario_id, 0), checkpoint_every=0)
    result = run_episode(mechanism=resolved.build_mechanism(),
                         policies=build_policies(resolved), config=config, paths=paths)
    assert result.status == "completed", result.failure_reason
    s = result.summary
    return {
        "utility": {a: Fraction(v) for a, v in s["utility"].items()},
        "quality": s["collective_quality"],
        "briefing": tuple((b["slot_id"], b.get("proposition_id")) for b in s["briefing"]),
        "credit": {a: Fraction(v) for a, v in s["individual_credit"].items()},
        "effort": dict(s["effort"]),
    }


def main() -> None:
    workdir = Path(tempfile.mkdtemp(prefix="chl-cert-"))
    results: dict[tuple, dict] = {}
    try:
        for acc, topo in INSTITUTIONS:
            for profile in itertools.product(STRATS, repeat=3):
                results[(acc, topo, profile)] = run_profile(acc, topo, profile, workdir)
    finally:
        shutil.rmtree(workdir, ignore_errors=True)

    lines = [
        "# Mechanism certificate — Evidence Commons v0",
        "",
        "Generated by `certificate.py` (deterministic enumeration; exact rational",
        "arithmetic; 32 sealed episodes). Parameters: the `ECParams` defaults in",
        "`scenarios/*.json` (rounds=12, costs inspect=1/share=1/propose=1/verify=2,",
        "collective +12/-12 per slot, credit +3/-3 propose, +2/-2 verify).",
        "**Utility weights are placeholders — final values are a HUMAN decision.**",
        "",
        "## C1 — Free-riding temptation (unilateral deviation contributor -> freerider)",
        "",
        "| institution | deviations tested | deviation gains (min..max) | temptation exists? |",
        "|---|---|---|---|",
    ]
    c1_summary = {}
    for acc, topo in INSTITUTIONS:
        gains = []
        for profile in itertools.product(STRATS, repeat=3):
            for i, strat in enumerate(profile):
                if strat != "contributor":
                    continue
                deviant = list(profile)
                deviant[i] = "freerider"
                u_c = results[(acc, topo, profile)]["utility"][AGENTS[i]]
                u_f = results[(acc, topo, tuple(deviant))]["utility"][AGENTS[i]]
                gains.append(u_f - u_c)
        exists = any(g > 0 for g in gains)
        c1_summary[(acc, topo)] = (gains, exists)
        lines.append(
            f"| {acc} x {topo} | {len(gains)} | {float(min(gains)):+.2f} .. "
            f"{float(max(gains)):+.2f} | {'YES' if exists else 'no'} |"
        )

    lines += [
        "",
        "## C2 — Collective stakes (all-contribute vs all-freeride)",
        "",
        "| institution | total U (all contribute) | total U (all freeride) | "
        "contribution collectively better? |",
        "|---|---|---|---|",
    ]
    for acc, topo in INSTITUTIONS:
        u_all_c = sum(results[(acc, topo, ("contributor",) * 3)]["utility"].values())
        u_all_f = sum(results[(acc, topo, ("freerider",) * 3)]["utility"].values())
        lines.append(f"| {acc} x {topo} | {float(u_all_c):.2f} | {float(u_all_f):.2f} "
                     f"| {'YES' if u_all_c > u_all_f else 'NO'} |")

    lines += [
        "",
        "## C3 — Intervention invariance (accountability changes attribution, not the task)",
        "",
        "For every behaviour profile and topology: aggregate vs attributable must give",
        "identical briefing, identical collective quality, identical TOTAL utility;",
        "only the per-agent credit split may differ.",
        "",
    ]
    violations = []
    redistributions = 0
    for topo in ("private", "shared_ledger"):
        for profile in itertools.product(STRATS, repeat=3):
            r_agg = results[("aggregate", topo, profile)]
            r_att = results[("attributable", topo, profile)]
            same_brief = r_agg["briefing"] == r_att["briefing"]
            same_quality = r_agg["quality"] == r_att["quality"]
            same_total = sum(r_agg["utility"].values()) == sum(r_att["utility"].values())
            if not (same_brief and same_quality and same_total):
                violations.append((topo, profile))
            if r_agg["credit"] != r_att["credit"]:
                redistributions += 1
    lines.append(f"- profiles checked: 16; violations: {len(violations)}"
                 + (f" — {violations}" if violations else ""))
    lines.append(f"- profiles where the credit SPLIT differs (expected): {redistributions}/16")
    lines += [
        "",
        "## Verdicts",
        "",
    ]
    c1_all = all(v[1] for v in c1_summary.values())
    lines.append(
        f"- **Social dilemma (within the enumerated strategy set): "
        f"{'CERTIFIED' if c1_all else 'PARTIAL'}** — free-riding temptation exists under "
        + ("every institution" if c1_all else
           "only: " + ", ".join(f"{a}x{t}" for (a, t), v in c1_summary.items() if v[1]))
        + ", while all-contribute beats all-freeride collectively (C2)."
    )
    lines.append(
        "- **Intervention integrity: " + ("CERTIFIED" if not violations else "VIOLATED")
        + "** — accountability redistributes credit without changing the task (C3)."
    )
    lines += [
        "",
        "## Simulation hypotheses (NOT certified — for the preregistration)",
        "",
        "- H1-type claims that attributable accountability INCREASES contribution rely on",
        "  agents that respond to attribution. The scripted personas here do not read",
        "  attribution, so behaviour is institution-invariant by construction; only LLM or",
        "  richer agents can test H1. This certificate only establishes that the incentive",
        "  landscape those agents face is a genuine dilemma with attribution-dependent",
        "  credit flows.",
        "- Claims about the full strategy space (e.g. no clever strategy escapes the",
        "  dilemma) are NOT certified: enumeration covered {contributor, freerider}^3.",
        "",
        "Every number above derives from sealed episode summaries; rerun `certificate.py`",
        "to regenerate byte-identical results (deterministic seeds).",
    ]
    out = STUDY_DIR / "MECHANISM_CERTIFICATE.md"
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out}")
    print(f"C1 dilemma everywhere: {c1_all}; C3 violations: {len(violations)}")


if __name__ == "__main__":
    main()
